"""Combine the per-chapter JSON files in this folder into ../data.js (window.CHAPTERS), in narrative order."""
import json, pathlib

here = pathlib.Path(__file__).parent
order = ["i", "ii", "iii", "iv", "v", "vi", "vii"]
chapters = {}
for f in sorted(here.glob("chapters-*.json")):
    for c in json.loads(f.read_text()):
        chapters[c["id"]] = c
missing = [i for i in order if i not in chapters]
if missing:
    raise SystemExit(f"missing chapters: {missing}")
out = "// Generated by content/build.py from content/chapters-*.json. Do not edit by hand.\nwindow.CHAPTERS = "
out += json.dumps([chapters[i] for i in order], ensure_ascii=False, indent=1) + ";\n"
(here.parent / "data.js").write_text(out)
template = (here / "eixo-template.html").read_text()
for n, cid in enumerate(order, 1):
    page = template.replace("__ID__", cid).replace("__NUM__", f"{n:02d}")
    (here.parent / f"eixo-{n:02d}.html").write_text(page)
print("data.js:", sum(len(s["items"]) for c in chapters.values() for s in c["sections"]), "items")
